// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Tel                  string   `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *CreateUserRequest) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserResponse struct {
	Affected             int64    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "com.txvier.srv.user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "com.txvier.srv.user.CreateUserResponse")
	proto.RegisterType((*Request)(nil), "com.txvier.srv.user.Request")
	proto.RegisterType((*Response)(nil), "com.txvier.srv.user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xad, 0xe9, 0xea, 0x3a, 0xa7, 0x75, 0xf4, 0x10, 0xca, 0x2e, 0x48, 0x0e, 0xea, 0x29,
	0x88, 0xfe, 0x04, 0x41, 0x3c, 0x17, 0x3c, 0x4b, 0xdc, 0x9d, 0x4a, 0x21, 0x69, 0x6a, 0x92, 0x56,
	0xff, 0x95, 0x7f, 0x51, 0x92, 0xd6, 0x2a, 0x58, 0xf5, 0xf6, 0xe6, 0xbd, 0x21, 0xdf, 0x4b, 0x02,
	0xd0, 0x79, 0x72, 0xb2, 0x75, 0x36, 0x58, 0x3c, 0xd9, 0x5a, 0x23, 0xc3, 0x5b, 0x5f, 0x93, 0x93,
	0xde, 0xf5, 0x32, 0x46, 0x42, 0xc1, 0xf1, 0xad, 0x23, 0x15, 0xe8, 0xc1, 0x93, 0x2b, 0xe9, 0xa5,
	0x23, 0x1f, 0x10, 0x21, 0x6f, 0x94, 0x21, 0x9e, 0x9d, 0x65, 0x97, 0x47, 0x65, 0xd2, 0xb8, 0x02,
	0xd6, 0xbe, 0xee, 0xf8, 0x7e, 0xb2, 0xa2, 0x8c, 0x4e, 0x20, 0xcd, 0xd9, 0xe0, 0x04, 0xd2, 0x78,
	0x0a, 0x0b, 0x32, 0xaa, 0xd6, 0x3c, 0x4f, 0xde, 0x30, 0x88, 0x2b, 0xc0, 0xef, 0x08, 0xdf, 0xda,
	0xc6, 0x13, 0x16, 0xb0, 0x54, 0x55, 0x45, 0xdb, 0x40, 0xbb, 0xc4, 0x61, 0xe5, 0x34, 0x8b, 0x0d,
	0x1c, 0xfe, 0x51, 0x45, 0xac, 0x61, 0x39, 0x1d, 0xb3, 0x02, 0x66, 0xfc, 0xf3, 0x18, 0x47, 0x79,
	0xfd, 0x9e, 0x41, 0x1e, 0x49, 0x78, 0x07, 0x8b, 0x7b, 0xd2, 0xda, 0xe2, 0x5a, 0xce, 0xdc, 0x5c,
	0x8e, 0x84, 0x62, 0xf3, 0x4b, 0x3a, 0x00, 0xc4, 0x1e, 0x3e, 0x02, 0x7c, 0xf5, 0xc7, 0xf3, 0xd9,
	0xf5, 0x1f, 0x6f, 0x58, 0x5c, 0xfc, 0xbb, 0xf7, 0x09, 0x78, 0x3a, 0x48, 0xff, 0x73, 0xf3, 0x11,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x2f, 0x82, 0xe9, 0xad, 0x01, 0x00, 0x00,
}
